openapi: '3.0.3'
info:
  title: API Demo2 Document
  version: '1.0'
  description:
    "API Demo2 <br />
    这个文件主要为了演示多个yaml时如何定义。"
servers:
  - url: http://localhost:8001/api/v1/demo
paths:
  /documents/:
    get:
      summary: 获取课程文档列表 2
      parameters:
        - $ref: '_parameters.yml#/page'
        - $ref: '_parameters.yml#/page_size'
        - $ref: '#parameters/course'
      responses:
        '200':
          description: 课程文档列表 2
          content:
            'application/json':
              schema:
                allOf:
                  - $ref: '_responses.yml#/definitions/PageResponse'
                  - type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/definitions/Document'


parameters:
  course:
    name: course
    in: query
    description: course_key, 课程id
    required: true
    schema:
      type: string

definitions:
  DocumentInnerCourse:
    type: object
    additionalProperties:
      type: boolean
    example:
      dict_key_string: false
  Document:
    type: object
    required:
      - url
      - courses
      - created
      - modified
      - document_id
    properties:
      url:
        type: string
        description: url
      courses:
        type: array
        items:
          $ref: '#/definitions/DocumentInnerCourse'
      document_id:
        type: string
        example:
          4adc611f-58b7-468b-9016-3f2c515024f1
      client_document_id:
        type: string
        example:
          api-design-ebook-2012-03.pdf
      pages:
        type: integer
      status:
        type: string
        example:
          upload
      error_description:
        type: string
      created:
        $ref: '_definitions.yml#/created'
      modified:
        $ref: '_definitions.yml#/modified'
